### ISSUE TITLE
Add csrf security

### ISSUE THREAD

**Issue by avakhov** [snowman-io/snowman-io#62]
http://stackoverflow.com/questions/11451161/sinatra-csrf-authenticity-tokens

**Comment by avakhov** [comment]
Or make unpacking/auth in ember app.

**Comment by keydunov** [comment]
I like the idea to make auth in ember, we can use [ember-simple-auth](https://github.com/simplabs/ember-simple-auth).

**Comment by avakhov** [comment]
ember-simple-auth looks good

**Comment by avakhov** [comment]
Auth is via simple-auth now
