### ISSUE TITLE
Generate token to sign http requests from agent

### ISSUE THREAD

**Issue by keydunov** [snowman-io/snowman-io#64]
It could be automatically generated during unpacking and be available in UI, so user can copy it and configure agent.

**Comment by avakhov** [comment]
Let create settings tab instead unused about. What do you think?

On Thursday, January 8, 2015, Artyom Keydunov <notifications@github.com>
wrote:

> It could be automatically generated during unpacking and be available in
> UI, so user can copy it and configure agent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowman-io/snowman-io/issues/64>.
>


-- 
Алексей Вахов

**Comment by keydunov** [comment]
Yes, it is good place for such things, do we need anything else to put in a settings tab right now?

**Comment by avakhov** [comment]
I don't know :)

**Comment by avakhov** [comment]
Done
