### ISSUE TITLE
Not a single unicode snowman on site or readme

### ISSUE THREAD

**Issue by kumavis** [snowman-io/snowman-io#75]
very dissapoint. :snowman:

**Comment by kumavis** [comment]
# ☃

**Comment by avakhov** [comment]
Fixed
https://github.com/snowman-io/snowman-io#contributing
![snowman-io_snowman-io](https://cloud.githubusercontent.com/assets/92554/9800263/b8f9965e-5814-11e5-8dd1-0d091f03811b.png)

**Comment by kumavis** [comment]
:confetti_ball: :fireworks: good work here.
